### ISSUE TITLE
Deep6

### ISSUE THREAD

**Issue by trevor2024** [malortie/SourceModPatcher#10]
Hi, please add support for Deep6:
https://archive.org/details/deep6

**Comment by malortie** [comment]
Looks valid.

I'll add support for it when I get to it.

Two things:

1. No server.cfg is provided by default. Without this file, the mod crashes. I'll provide a default one.
2. The mod doesn't feature a 'Create server' menu option. I'll add one.

Feel free to submit other Source mods (not standalone games) you wish to see added.

Thanks.

________________________________
From: Trevor ***@***.***>
Sent: Wednesday, December 18, 2024 5:46 PM
To: malortie/SourceModPatcher ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [malortie/SourceModPatcher] Deep6 (Issue #10)


Hi, please add support for Deep6:
https://archive.org/details/deep6

**Comment by malortie** [comment]
@trevor2024

Support for Deep6 has been added. It'll be available in the next release (v0.4.0).

See the following commits:

2ffe6e20eec7086c409b2147ab0c2939b2aed3fc
c692b98193f55fb990f9f4fe6e2d69fe3c18aa80
48a560b96f135468d4c39991500f561879bd4a2b
a50cd2735ddb2735914b0502d9286fac74d21845
4eb1a128d5d1259e7348b9119c8330b2148dd7fc

**Comment by malortie** [comment]
@trevor2024

SourceModPatcher v0.4.0 has been [released](https://github.com/malortie/SourceModPatcher/releases/tag/sourcemodpatcher%2Fv0.4.0). You should be able to play Deep6.

Video: https://www.youtube.com/watch?v=jIiiH4lRcFA
